#!/usr/bin/python3
# -*- coding: utf-8 -*-

import os, sys, email, getpass
import email.generator

import modules

from mailhelper.functions import parseSender, parseHeader, replyStatus
from constants import MAIN_EMAIL_ADDRESS, FROM_FOR_MAILS

ALLOWED_MAILADDRESSES=['yourmail@gmail.com','yourmail@yahoo.com', 'me@work.biz'] # only mails from these addresses will be accepted

SUBJECT_FOR_REPLY='[PIM] Status'

BASEPATH = './'
SAVEMAIL = os.path.join(BASEPATH,'lastmail') # kind-of-debug-feature. this file holds the last mail received. 
REPLYSIGNS=('re:','aw:') # prefixes for answered mails


def initLogger():
    import logging
    logger = logging.getLogger('mainreceiver')
    hdlr = logging.FileHandler(os.path.join(BASEPATH,'pim.log'))
    formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')
    hdlr.setFormatter(formatter)
    logger.addHandler(hdlr) 
    logger.setLevel(logging.INFO)
    return logger

logger = initLogger()


msg = email.message_from_file(sys.stdin)
accept = False

sender = parseSender(msg['from'])
if sender == 'unknown':
  logger.warn('could not parse sender from %s', msg['from'])
  sys.exit(1)

# accept message?
for recip in ALLOWED_MAILADDRESSES:
  if recip in sender:
    sender = recip
    accept = True
    break
if not accept: 
  if logger is not None: logger.info('declining mail from %s', sender)
  replyStatus(MAIN_EMAIL_ADDRESS,'incoming reminder from unallowed mail: '+sender+'\n', subj = SUBJECT_FOR_REPLY, sender = FROM_FOR_MAILS)
  sys.exit(1)

logger.info('running as %s', getpass.getuser())
logger.info('accepting mail')

if SAVEMAIL != '':
  try:
   out = open(SAVEMAIL, 'w', encoding='utf-8')
  except IOError as ioe:
   pass
  else:
   with out:
     generator = email.generator.Generator(out)
     generator.flatten(msg)
     out.close()

subj = parseHeader(msg['Subject'])
logger.info('mail has subj '+subj)

isreply = any(subj.startswith(word) for word in REPLYSIGNS)
if not isreply:
  if modules.receive(subj,msg):
    logger.info("successfully handled mail")
    sys.exit(0)
elif isreply:
  if modules.receivereply(subj,msg):
    logger.info("successfully handled mail")
    sys.exit(0)
else:
  logThis = 'could not determine action. msg-subject was \''+msg['Subject']+'\' - parsed to \''+subj+'\')'
  logger.warn(logThis)
  replyStatus(sender, logThis, subj = SUBJECT_FOR_REPLY, sender = FROM_FOR_MAILS)
  sys.exit(1)
