#!/usr/bin/python
# -*- coding: utf-8 -*-

BASEPATH='./'

SUBJECT='Teux Deux'
TEXT='''Good Morning Mirco!

$body

Regards,
Your Computer
'''
REMINDERLINE='* %s\n'


from string import Template
from subprocess import Popen, PIPE
import locale
try:
  locale.setlocale(locale.LC_ALL, 'de_DE')
except locale.Error:
  try:
    locale.setlocale(locale.LC_ALL, 'de_DE.utf8')
  except locale.Error:
    print "both de_DE and de_DE.utf8 could not be set"

import modules
from mailhelper.MIMEUTF8QPText import MIMEUTF8QPText

from constants import MAIN_EMAIL_ADDRESS, FROM_FOR_MAILS

mailtext={'body':''}

for o in modules.getoutput():
  if o:
    mailtext['body'] += "\n\n{}".format(o.strip()) if mailtext['body'] is not '' else o.strip()

if not mailtext['body'] == '':
  mail = MIMEUTF8QPText(Template(TEXT).substitute(mailtext))
  mail['Subject'] = SUBJECT
  mail['From'] = FROM_FOR_MAILS
  mail['To'] = MAIN_EMAIL_ADDRESS
  print mail
  #p = Popen(["/usr/sbin/sendmail", "-t", "-oi"], stdin=PIPE)
  #p.communicate(mail.as_string())
